[package]
name = "musiclibrary-vip"
version = "1.0.0"
description = "Music Library VIP - Search and discover music tracks with instant search and pagination"
license = "MIT"
homepage = "https://github.com/itsShalard/musiclibrary-vip"

[dependencies]
python = "3.11"

[fs]
"/public" = "dist"

[commands.build]
runner = "https://webc.org/runner/node@18"
cmd = ["sh", "-c", "npm ci && npm run build"]

[commands.start]
runner = "https://webc.org/runner/python@3.11"
cmd = ["python", "-m", "http.server", "8000", "--directory", "/public"]

[[commands.start.annotations]]
wasm.env = "PORT=8000"

[build]
command = "npm run build"
output-dir = "dist"

[deploy]
exclude = [
  "node_modules",
  ".git",
  ".DS_Store",
  "*.log",
  ".astro",
  ".vscode"
]